
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /static
  static_dir: static

- url: /bootstrap
  static_dir: bootstrap

- url: /.*
  script: RESTful_cloud_API.app

# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: django
  version: latest
- name: flask
  version: latest
# [END libraries]
